# Generated by Django 5.2.5 on 2025-08-22 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order_payment_method_order_pickup_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='pickuppoint',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Метод оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время самовывоза'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='ID транзакции'),
        ),
        migrations.AlterField(
            model_name='order',
            name='voucher_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
