# Generated by Django 5.2.5 on 2025-08-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_name_ingredient_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_best_seller',
            field=models.BooleanField(default=False, verbose_name='Бестселлер'),
        ),
    ]
