# Generated by Django 5.2.5 on 2025-08-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_is_best_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Card', 'Карта'), ('Cash', 'Наличные'), ('Online', 'Онлайн-платёж')], max_length=30, null=True, verbose_name='Метод оплаты'),
        ),
    ]
