# Generated by Django 5.2.5 on 2025-08-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RemoveField(
            model_name='order',
            name='pickup_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='voucher_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='card_cvv',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='CVV'),
        ),
        migrations.AddField(
            model_name='order',
            name='card_expiry',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Срок действия (MM/YY)'),
        ),
        migrations.AddField(
            model_name='order',
            name='card_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя на карте'),
        ),
        migrations.AddField(
            model_name='order',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Номер карты'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон (для MBank)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Card', 'Карта'), ('Cash', 'Наличные'), ('Online', 'Онлайн-платёж')], max_length=20, null=True, verbose_name='Метод оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ID транзакции'),
        ),
    ]
