# Generated by Django 5.2.5 on 2025-08-28 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_coffeeshop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coffeeshop',
            options={'verbose_name': 'О кофейне', 'verbose_name_plural': 'О кофейнях'},
        ),
    ]
