# Generated by Django 5.2.5 on 2025-08-21 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='level',
        ),
    ]
